# Generated by Django 3.1.2 on 2020-10-31 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('cui', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('tipoPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registroPersona.tipopersona')),
            ],
        ),
    ]
