# Generated by Django 3.1.2 on 2020-11-12 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.CharField(max_length=100)),
                ('costo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPersona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('tipoDocumento', models.CharField(max_length=100)),
                ('documento', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('edad', models.CharField(max_length=100)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrations.evento')),
                ('tipoPersona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrations.tipopersona')),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='tipoEvento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='migrations.tipoevento'),
        ),
    ]
